### ISSUE TITLE
Add Portfolio Optimizer API resource?

### ISSUE THREAD

**Issue by lequant40** [wilsonfreitas/awesome-quant#125]
Hello there,

In addition to being the creator of the _portfolio-allocation_ JavaScript library you mention here (thanks :-)), I am also providing a (free) portfolio analysis and optimization API called _Portfolio Optimizer_ at [https://portfoliooptimizer.io/](https://portfoliooptimizer.io/).

If you think this one qualifies to help your quant audience, I could certainly do a PR to add it in the FrameWorks section.

Just let me know.

Cheers,

Roman

**Comment by lequant40** [comment]
@wilsonfreitas, I made the following proposal PR: https://github.com/wilsonfreitas/awesome-quant/pull/128

**Comment by wilsonfreitas** [comment]
Done thanks!

**Comment by lequant40** [comment]
Thanks as well!!
