### ISSUE TITLE
Consider LEAN/QC For Python

### ISSUE THREAD

**Issue by jaredbroad** [wilsonfreitas/awesome-quant#131]
Hi @wilsonfreitas, thanks for the awesome list!

Please consider the LEAN project for the Python section, 95% of our 200K users are python users. 

lean.io is the open-source project (or https://github.com/QuantConnect/Lean) // quantconnect.com for the platform

**Comment by ikamanu** [comment]
+1

**Comment by wilsonfreitas** [comment]
Done! Thanks!
