### ISSUE TITLE
Add Finalytics Rust and Python Libraries

### ISSUE THREAD

**Issue by Nnamdi-sys** [wilsonfreitas/awesome-quant#174]
I created a Library for Financial Analytics in Rust and a Python Extension using Py03.

I would like to Include it in this repo.

Home Page: https://finalytics.rs/

Rust Github Repository: https://github.com/Nnamdi-sys/finalytics

Python Github Repository: https://github.com/Nnamdi-sys/finalytics-py

**Comment by wilsonfreitas** [comment]
Repo added ... thanks.
