### ISSUE TITLE
Implementation of the Hierarchical Equal Risk Contribution Method (R Shiny)

### ISSUE THREAD

**Issue by YannickKae** [wilsonfreitas/awesome-quant#175]
Have implemented Raffinot's (2018) **HERC** approach as an interactive **_R Shiny web application_** & would like to point out that it might fit here under "_**Replications**_" if it meets the requirements.

Here is the GitHub repository for it: [Github Repository](https://github.com/YannickKae/Statistical-Learning-based-Portfolio-Optimization)
Here is the link to the application: [Web App](https://yannickkaelber.shinyapps.io/StatisticalLearningPortfolioOptimization/)

**Comment by wilsonfreitas** [comment]
Repo added ... thanks.
