### ISSUE TITLE
New community active forks of Quantopian projects no longer maintained

### ISSUE THREAD

**Issue by rsheftel** [wilsonfreitas/awesome-quant#180]
Since quantopian went bankrupt they are no longer maintaining their packages PyFolio and Empyrical. There are new forked versions that your list should be updated to link to:

https://github.com/stefan-jansen/empyrical-reloaded

https://github.com/stefan-jansen/pyfolio-reloaded

**Comment by wilsonfreitas** [comment]
Done thanks
