### ISSUE TITLE
Addition: python > indicators

### ISSUE THREAD

**Issue by mr-easy** [wilsonfreitas/awesome-quant#182]
[streaming-indicators](https://github.com/mr-easy/streaming_indicators)

A python library for computing technical analysis indicators on streaming data.

**Comment by femtotrader** [comment]
Looks quite similar to [talip](https://github.com/nardew/talipp)

**Comment by wilsonfreitas** [comment]
Added here 02186643d547981d45a50910be2d66683588a786 and here 4b80bd1c0657342f7175d8fb1a6b0f647e1b0da2
