### ISSUE TITLE
Addition to Python Risk Analysis

### ISSUE THREAD

**Issue by antonvorobets** [wilsonfreitas/awesome-quant#184]
The fortitudo.tech Python package available at: https://github.com/fortitudo-tech/fortitudo.tech.

Enables people to perform Entropy Pooling views and stress-testing as well as CVaR optimization for fully general Monte Carlo distributions.

For a quick introduction to this functionality, see: https://medium.com/@ft_anvo/entropy-pooling-and-cvar-portfolio-optimization-in-python-ffed736a8347

**Comment by wilsonfreitas** [comment]
Added here 572208a7c86a3ac08588adeac6129b05d50be03b 
tks
