### ISSUE TITLE
Recommend zipline-reloaded and alphalens-reloaded

### ISSUE THREAD

**Issue by FreeZIngMoon11** [wilsonfreitas/awesome-quant#199]
SInce Quantopian stopped updating their packages years ago, Mr Jansen created these reloaded branches and keeps updating. They newest version should be compatible with Numpy 2.0 and other updated finmath packages.

The pyfolio-reloaded is already listed, here are the links to zipline-reloaded and alphalens-reloaded

https://github.com/stefan-jansen/zipline-reloaded
https://github.com/stefan-jansen/alphalens-reloaded

**Comment by wilsonfreitas** [comment]
Done!
