### ISSUE TITLE
Yahoo Finance / Google Finance Depreciated. Possible Alternatives

### ISSUE THREAD

**Issue by addisonlynch** [wilsonfreitas/awesome-quant#26]
Yahoo Finance/YQL and Google Finance APIs for time series data are deprecated as of 1/2018. Would recommend IEX or AlphaVantage as an alternative. Python wrapper available http://github.com/addisonlynch/iexfinance and also AlphaVantage https://github.com/RomelTorres/alpha_vantage

**Comment by rsvp** [comment]
Possible alternatives are discussed in detail at 
https://github.com/rsvp/fecon235/issues/7
