### ISSUE TITLE
Add ynouri/pySABR

### ISSUE THREAD

**Issue by ynouri** [wilsonfreitas/awesome-quant#30]
Hi Wilson,
Thanks for the awesome list! Just wanted to share some of my recent work, I think it might have a place in your list. [ynouri/pysabr](https://github.com/ynouri/pysabr) implements SABR volatility model, which is widely used for interest rate options such as swaptions and cap/floors.

**Comment by wilsonfreitas** [comment]
Done
Thanks for contributing.
BTW I use this model a lot here in Brazil.
I find out that sabr presents really good fits for some options on indexes.
