### ISSUE TITLE
Github topics

### ISSUE THREAD

**Issue by femtotrader** [wilsonfreitas/awesome-quant#52]
Here is some Github topics to follow to improve this repository

https://github.com/topics/trading-algorithms?o=desc&s=stars
https://github.com/topics/algotrading?o=desc&s=stars
https://github.com/topics/algorithmic-trading-engine?o=desc&s=stars
https://github.com/topics/quant?o=desc&s=stars
https://github.com/topics/finance?o=desc&s=stars
https://github.com/topics/trading-bot?o=desc&s=stars
https://github.com/topics/technical-analysis?o=desc&s=stars
https://github.com/topics/arbitrage-bot?o=desc&s=stars

**Comment by wilsonfreitas** [comment]
I've update with a few.
Thanks.
