### ISSUE TITLE
add akshare

### ISSUE THREAD

**Issue by jindaxiang** [wilsonfreitas/awesome-quant#55]
hello, akshare(https://github.com/jindaxiang/akshare) is a tool for downloading chinese futures data

**Comment by yutiansut** [comment]
just a copy of another project (https://github.com/LowinLi/fushare) and removed the git commit history @wilsonfreitas

**Comment by yutiansut** [comment]
https://github.com/jindaxiang/akshare/commit/b1a2d57d75c0fab8437a1aff45f4dbe4fc88321f

**Comment by jindaxiang** [comment]
yes, akshare's **firtst version** is clone from the fushare, because the author of fushare can not be connected and the code in fushare can not run normally. So i write another package named akshare to fix the errors in source code and normalize the api,  and recently update more than 10 apis.
This is the latest document: [AkShare Document](https://akshare.readthedocs.io/) 
so it is not just a copy and will provide more apis
