### ISSUE TITLE
Importing R packages into Python

### ISSUE THREAD

**Issue by sethberlin** [wilsonfreitas/awesome-quant#56]
Just wondering if anyone has any suggestions for importing R packages into Python.  I have been using the RPY2 package.  Also, tried looking at my R paths (R_Home) and .libPaths().  Even when I put the correct ".lib_loc" code in IMPORTR code, I still have issues loading packages.

Interestingly enough, I can load some R packages (RiskParity portfolio, timeSeries, etc...) and not others.

Figured anyone looking at this great list of R and Python tools would have ideas.  Thanks for ideas.

**Comment by wilsonfreitas** [comment]
I am using rpy2 usually. I do a lot of knitr using it, and the path settings is a nightmare. I believe there isn't an easy path.
