### ISSUE TITLE
Take a look at QuantMath?

### ISSUE THREAD

**Issue by MarcusRainbow** [wilsonfreitas/awesome-quant#82]
QuantMath is a library I have been working on, written in Rust. It is mainly aimed at risk-neutral pricing of Equity options at the moment, though its architecture could be very easily extended to handle rates, commodities and FX. It currently has Monte-Carlo and analytic pricers for a number of different products. One area where it is pretty strong is support for different risk measures. It can be interfaced to from C or C++, and there is also an Excel wrapper library using the Excel 12 api.

https://github.com/MarcusRainbow/QuantMath

**Comment by wilsonfreitas** [comment]
Done!
