### ISSUE TITLE
Take a look at Haxcel?

### ISSUE THREAD

**Issue by MarcusRainbow** [wilsonfreitas/awesome-quant#83]
Not strictly speaking a quant library, Haxcel uses the Excel 12 interface to allow you to run Haskell inside a spreadsheet. You can write your own Haskell or pull in one of the open-source Haskell pricing libraries already available in awesome-quant, by loading external modules. You can mix and match Haskell and Excel formulae, and what you write in Haskell supports non-strict evaluation. For example array formulae are only evaluated to the extent that they are needed for the cell range to be filled.

**Comment by MarcusRainbow** [comment]
Sorry, I missed out the URL -- https://github.com/MarcusRainbow/Haxcel

**Comment by wilsonfreitas** [comment]
Done
