### ISSUE TITLE
Link to DRIP (Github)

### ISSUE THREAD

**Issue by lakshmiDRIP** [wilsonfreitas/awesome-quant#9]
Hi – I am wondering if there is a way we can get links to DRIP – a fixed income/asset allocation/transaction cost analytics system – into awesome-quant, i.e., https://github.com/wilsonfreitas/awesome-quant
 
https://lakshmidrip.github.io/DRIP
https://github.com/lakshmiDRIP/DRIP
 
It is Open-Source Java, and has a number of users in NY/London/Tokyo.
 
Lakshmi (lakshmi7977@gmail.com)

**Comment by wilsonfreitas** [comment]
Done 3f961f3.
Thanks for contributing.
