### ISSUE TITLE
Statmetrics

### ISSUE THREAD

**Issue by Vinnitschenko** [wilsonfreitas/awesome-quant#94]
Please consider adding **[Statmetrics](https://github.com/Vinnitschenko/Statmetrics-Android/)** to your outstanding repository.

Statmetrics is a free Android app for portfolio and investment analytics:
- Advanced charting and technical analysis toolkit
- Interactive portfolio construction, analysis and optimization
- Quantitative performance and risk analysis of portfolio and portfolio components
- Mean-variance portfolio optimization (minimum-variance, maximum diversification, equal risk contribution, etc.)
- Visualization of portfolio components, efficient frontier and risk metrics
- Calculation of investment risk indicators (Information Ratio, Alpha, Beta, Value at Risk, etc.).
- Exploratory Data Analysis (Descriptive Statistics, Correlation and Cointegration Analysis, PCA, Unit Root and Granger Causality Test, etc.)

**https://github.com/Vinnitschenko/Statmetrics-Android/**
**https://play.google.com/store/apps/details?id=org.statmetrics.app**

**Comment by wilsonfreitas** [comment]
You have a great software here, but the list is a reference for projects and code.
